spring:
  datasource:
    username: postgres
    password: root
  flyway:
    enabled: false
    ignore-missing-migrations: true
    locations: classpath:/db/migrations
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    url: "jdbc:postgresql://localhost:5432/elinext"
    user: postgres
    password: root
  freemarker:
    expose-request-attributes: true
    suffix: .ftl
datasource:
  driverName: org.postgresql.Driver
  url: "jdbc:postgresql://localhost:5432/elinext"
  login: postgres
  password: root
  initialSize: 10
  maxActive: 7
